api_version = "2025-07"

[[extensions]]
uid = "616cac44-d0a2-71df-af0c-ca1793419c703adcbcsd"
type = "ui_extension"
name = "backend-box"
handle = "backend-box"

[[extensions.targeting]]
module = "./src/index.tsx"
target = "purchase.checkout.reductions.render-after"

[extensions.capabilities]
api_access = true
network_access = true
block_progress = true
[[metafields]]
namespace = "custom"
key       = "backend_token"
ownerType = "customer"

[[metafields]]
namespace = "custom"
key       = "is_old_user"
ownerType = "customer"